on: issues
name: Create Default Labels
jobs:
  labels:
    name: CreateLabels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: lannonbr/issue-label-manager-action@3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
